# Generated by Django 4.0.2 on 2022-02-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippets',
            new_name='Snippet',
        ),
        migrations.AlterModelTable(
            name='snippet',
            table='Snippet',
        ),
    ]
